[project]
name = "cs2-storage-unit-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jakub Gawron", email = "203234060+JakubGawron@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "babel>=2.18.0",
    "price-parser>=0.5.1",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "tomli-w>=1.2.0",
]

[project.scripts]
cs2-storage-unit-tracker = "cs2_storage_unit_tracker.cli.app:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
