["Fracture Case"]
link = "https://steamcommunity.com/market/listings/730/Fracture%20Case"
quantity = 50
purchase_price_per_item = "0.00"

["Dreams & Nightmares Case"]
link = "https://steamcommunity.com/market/listings/730/Dreams%20%26%20Nightmares%20Case"
quantity = 40
purchase_price_per_item = "0.00"

["Revolution Case"]
link = "https://steamcommunity.com/market/listings/730/Revolution%20Case"
quantity = 30
purchase_price_per_item = "0.00"

["Recoil Case"]
link = "https://steamcommunity.com/market/listings/730/Recoil%20Case"
quantity = 20
purchase_price_per_item = "0.00"

["Clutch Case"]
link = "https://steamcommunity.com/market/listings/730/Clutch%20Case"
quantity = 10
purchase_price_per_item = "0.00"

["Snakebite Case"]
link = "https://steamcommunity.com/market/listings/730/Snakebite%20Case"
quantity = 20
purchase_price_per_item = "0.00"

["Gallery Case"]
link = "https://steamcommunity.com/market/listings/730/Gallery%20Case"
quantity = 30
purchase_price_per_item = "0.00"